spring:
  application:
    name: carrinho-compras

  data:
    mongodb:
      host: localhost
      port: 27017
      database: carrinho-compras
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000